// boss_final_exams.js
// ================================================================
// 15‑Fragen‑Abschlussprüfungen (Boss‑Quizzes) für jeden 3‑Monats‑Block
// ================================================================

/* ----------------------------------------------------------------
   BLOCK 1‑3 – Das Unternehmen & die eigene Rolle
   ---------------------------------------------------------------- */
export const boss_betrieb_rolle = [
  { id:'br_boss_q1', category:'boss-betrieb-rolle',
    question:'In einer Matrixorganisation erhält ein Entwickler zwei widersprüchliche Vorgaben: Der funktionale Vorgesetzte fordert Sicherheits‑Reviews, der Projektleiter drängt auf schnelle Auslieferung. Welches Vorgehen entspricht guter Governance?',
    choices:['Projektleiter priorisieren, da Time‑to‑Market entscheidend ist','Entwickler entscheidet selbstständig situativ','Konflikt eskalieren an gemeinsames Steering‑Komitee','Funktionalen Vorgesetzten ignorieren, da Projektziele Vorrang haben'],
    answer:2,
    explanation:'In Matrixstrukturen regelt ein Steering-/Lenkungsausschuss Zielkonflikte zwischen gleichrangigen Weisungslinien.' },
  { id:'br_boss_q2', category:'boss-betrieb-rolle',
    question:'Welche Kennzahl kombiniert Qualität, Kosten und Zeit zur ganzheitlichen Bewertung der Team‑Performance?',
    choices:['Return on Investment (ROI)','Earned Value (EV)','Net Present Value (NPV)','Total Cost of Ownership (TCO)'],
    answer:1,
    explanation:'Earned‑Value‑Analyse verbindet Fertigstellungsgrad (Zeit), Budget (Kosten) und gelieferte Scope‑Qualität.' },
  { id:'br_boss_q3', category:'boss-betrieb-rolle',
    question:'Nach Tuckman befindet sich dein Team im „Storming“. Welche Maßnahme beschleunigt den Übergang in „Norming“ am wirksamsten?',
    choices:['Einzelboni für schnellste Entwickler','Klare Rollen- und Verantwortlichkeits‑Workshops','Entfernung weniger produktiver Mitglieder','Daily‑Stand‑ups abschaffen'],
    answer:1,
    explanation:'Transparente Rollenklärung reduziert Konflikte und fördert Teamnormen.' },
  { id:'br_boss_q4', category:'boss-betrieb-rolle',
    question:'Ein Betriebsrat fordert Einsicht in Projektcontrolling‑Daten. Welche Rechtsgrundlage stützt das Auskunftsrecht?',
    choices:['§ 80 Abs. 2 BetrVG','DSGVO Art. 6 lit. f – berechtigtes Interesse','Handelsgesetzbuch § 238','BBiG § 14'],
    answer:0,
    explanation:'§ 80 (2) BetrVG verpflichtet den Arbeitgeber, dem Betriebsrat erforderliche Unterlagen bereitzustellen.' },
  { id:'br_boss_q5', category:'boss-betrieb-rolle',
    question:'Beim Vergleich Linien‑ vs. Netzwerkorganisation gilt welcher Zusammenhang?',
    choices:['Netzwerkorganisation steigert Skalenvorteile durch Zentralisierung','Linienorga minimiert Kommunikationswege über Abteilungsgrenzen','Netzwerkorganisation fördert Innovationsfähigkeit durch lose Kopplung','Linienorga erleichtert Kooperation mit externen Partnern'],
    answer:2,
    explanation:'Lose gekoppelte Netzwerke begünstigen schnellen Wissensaustausch und Innovation.' },
  { id:'br_boss_q6', category:'boss-betrieb-rolle',
    question:'Welcher Führungsstil ist nach Blanchard („Situatives Führen“) angemessen, wenn eine Fachkraft sehr kompetent, aber wenig motiviert ist?',
    choices:['Telling (S1)','Selling (S2)','Participating (S3)','Delegating (S4)'],
    answer:2,
    explanation:'Bei hoher Kompetenz, geringer Motivation: partizipativ unterstützen (S3).' },
  { id:'br_boss_q7', category:'boss-betrieb-rolle',
    question:'Im Projekt‑Netzplan verschiebt sich ein Vorgang mit Gesamtpuffer = 0 um 2 Tage nach hinten. Welche direkte Auswirkung?',
    choices:['Projektende verschiebt sich um 2 Tage','Freier Puffer eines parallelen Vorgangs reduziert sich','Gesamtpuffer steigt auf 2 Tage','Kritischer Pfad wechselt'],
    answer:0,
    explanation:'Kritische Vorgänge verzögern das Gesamtprojekt um den gleichen Zeitraum.' },
  { id:'br_boss_q8', category:'boss-betrieb-rolle',
    question:'Welche Aussage zur Prokura trifft zu?',
    choices:['Sie erlaubt Grundstücksveräußerung ohne Zusatzvollmacht','Sie kann nur einzeln erteilt werden','Sie darf im Innenverhältnis frei beschränkt, nach außen jedoch nicht beschränkt werden','Sie endet automatisch mit Ablauf eines Jahres'],
    answer:2,
    explanation:'Beschränkungen wirken nur intern, extern gilt § 50 HGB.' },
  { id:'br_boss_q9', category:'boss-betrieb-rolle',
    question:'Welche Kommunikationsform verhindert „Flurfunk“ und Informationsverluste am effektivsten?',
    choices:['One‑pager‑Memos per E‑Mail','Regelmäßige, cross‑funktionale Synchronsitzungen mit Time‑Box','Hierarchische Kettenbriefe','Ad‑hoc‑Chatnachrichten'],
    answer:1,
    explanation:'Time‑Box‑Meetings mit allen Stakeholdern sichern direkten, vollständigen Informationsfluss.' },
  { id:'br_boss_q10',category:'boss-betrieb-rolle',
    question:'In einer SCRUM‑Retrospektive stellt das Team wachsende „Work in Progress“-(WIP)-Zahlen fest. Welcher Lean‑Ansatz adressiert dieses Problem?',
    choices:['Kaizen‑Blitz','Kanban‑WIP‑Limits','5 Why‑Analyse','Poka‑Yoke'],
    answer:1,
    explanation:'Kanban setzt explizite WIP‑Grenzen zur Durchsatz‑Optimierung.' },
  { id:'br_boss_q11',category:'boss-betrieb-rolle',
    question:'Ein Datenschutz‑Verstoß wird dem Team gemeldet. Welche **richtige Reihenfolge** ist nach DSGVO Art. 33 einschlägig?',
    choices:['Meldung Betroffener → Behörde → Dokumentation','Dokumentation → Behörde innerhalb 72 h → Betroffene informieren','Behörde → Betroffene → Dokumentation','Behörde informieren, Betroffene nur bei hohem Risiko'],
    answer:1,
    explanation:'Datenschutzverletzungen müssen binnen 72 h der Aufsichtsbehörde gemeldet, dokumentiert und Betroffene ggf. informiert werden.' },
  { id:'br_boss_q12',category:'boss-betrieb-rolle',
    question:'Welche Kennzahl misst **Team‑Reife** nach Tuckman quantitativ?',
    choices:['Velocity‑Varianz','Team Cohesion Index (TCI)','Defect Escape Rate','Bus Factor'],
    answer:1,
    explanation:'Der Team‑Cohesion‑Index misst Zusammenhalt und korreliert mit der Performing‑Phase.' },
  { id:'br_boss_q13',category:'boss-betrieb-rolle',
    question:'Ein Projektbudget ist zu 60 % verbraucht, Fertigstellungsgrad laut Earned‑Value = 40 %. Welcher CPI (Cost Performance Index) ergibt sich?',
    choices:['0,67','1,5','0,4','1,25'],
    answer:0,
    explanation:'CPI = EV / AC = 0,4 / 0,6 ≈ 0,67 (< 1 = Kostenüberschreitung).' },
  { id:'br_boss_q14',category:'boss-betrieb-rolle',
    question:'Welche Rechtsfolge hat ein **verdeckter Mangel** beim Werkvertrag nach BGB, wenn er erst 18 Monate später entdeckt wird?',
    choices:['Anspruch erloschen, da Gewährleistung 12 Monate','Verjährung beginnt mit Ablieferung, Anspruch verjährt nach 2 Jahren','Verjährung beginnt mit Entdeckung, Anspruch besteht noch','Werkunternehmer haftet unbegrenzt'],
    answer:1,
    explanation:'Bei Werkleistungen gilt i.d.R. 2‑jährige Verjährung ab Abnahme (§ 634a BGB).' },
  { id:'br_boss_q15',category:'boss-betrieb-rolle',
    question:'Welches Meeting‑Format reduziert Entscheidungslatenz in cross‑funktionalen Teams am meisten?',
    choices:['Weekly Reports per E‑Mail','Command‑&‑Control‑Status‑Calls','Obeya‑Room mit physischem Task‑Board','Quartals‑Roadmap‑Workshops'],
    answer:2,
    explanation:'Der Obeya‑Room bündelt alle Entscheider täglich, Entscheidungen fallen sofort.' }
];

/* ----------------------------------------------------------------
   BLOCK 4‑6 – Arbeitsplätze & Wirtschaftlichkeit
   ---------------------------------------------------------------- */
export const boss_work_economy = [
  { id:'we_boss_q1', category:'boss-work-economy',
    question:'Ein Upgrade von 100 Office-PCs reduziert den durchschnittlichen Stromverbrauch pro Gerät von 70 W auf 45 W (8 h Betrieb, 220 Tage/Jahr, 0,32 €/kWh). Wie hoch ist die jährliche Ersparnis?',
    choices:['≈ 5 400 €','≈ 8 480 €','≈ 12 320 €','≈ 15 600 €'],
    answer:1,
    explanation:'ΔP = 25 W → 0,025 kW × 8 h × 220 d × 100 × 0,32 € ≈ 8 480 €.' },
  { id:'we_boss_q2', category:'boss-work-economy',
    question:'Welche BIOS‑Einstellung muss für die Installation eines modernen NVMe‑OS zwingend aktiviert sein?',
    choices:['Legacy CSM','UEFI‑Boot & GPT','Secure Boot deaktivieren','ACPI S3'],
    answer:1,
    explanation:'NVMe‑Boot benötigt UEFI mit GPT‑Partitionierung.' },
  { id:'we_boss_q3', category:'boss-work-economy',
    question:'Die ABC‑Analyse zeigt, dass 10 % der Ersatzteile 75 % des Kapitalbindungswerts ausmachen. Welchen dispositiven Schluss ziehst du?',
    choices:['Aufstockung der Lagerbestände dieser Teile','Reduktion der Sicherheitsbestände, enges Lieferanten‑VMI','Keine Änderung, da Ersatzteile kritisch','Ersatz durch günstigere Alternativteile'],
    answer:1,
    explanation:'Hoher Kapitalbindungsanteil → just‑in‑time / Vendor‑Managed‑Inventory senkt Lagerkosten.' },
  { id:'we_boss_q4', category:'boss-work-economy',
    question:'Welches Abschreibungsverfahren generiert **die höchste Kostenbelastung im ersten Jahr** für einen 120 000 €‑Server (Nutzungsdauer 5 J.)?',
    choices:['Lineare AfA','Doppelt‑degressive AfA','Leistungsabschreibung','Sum-of-Years-Digits'],
    answer:1,
    explanation:'Die doppelt‑degressive Methode schreibt in den ersten Jahren am stärksten ab.' },
  { id:'we_boss_q5', category:'boss-work-economy',
    question:'Welche Kennzahl ist am BESTEN geeignet, um den wirtschaftlichen Nutzen eines Ergonomie‑Programms (höhenverstellbare Tische, Anti‑Fatigue‑Mats) **als Gesundheits‑ROI** darzustellen?',
    choices:['Cost‑Benefit‑Ratio','Net Present Value (NPV)','Return‑on‑Prevention (RoP)','Total‑Cost‑of‑Ownership (TCO)'],
    answer:2,
    explanation:'RoP vergleicht Präventionskosten mit vermiedenen Krankheits‑/ Ausfallkosten.' },
  { id:'we_boss_q6', category:'boss-work-economy',
    question:'Eine SSD hat eine MTBF von 1,8 Mio. h, eine HDD 0,8 Mio. h. Bei 500 Laufwerken im Dauerbetrieb (24 h) liegt die erwartete **Ausfallrate pro Jahr** der SSDs bei …',
    choices:['≈ 2,4 Geräten','≈ 4,9 Geräten','≈ 12,2 Geräten','≈ 15,8 Geräten'],
    answer:1,
    explanation:'λ = 1/MTBF; λ_SSD = 5,56 × 10⁻⁷ h⁻¹ → 500×24×365×λ ≈ 4,9 Ausfälle/Jahr.' },
  { id:'we_boss_q7', category:'boss-work-economy',
    question:'Welcher Posten gehört NICHT direkt zum **Total Cost of Ownership** eines Arbeitsplatzrechners?',
    choices:['Energieverbrauch','Erstinstallation & Imaging','Versicherung des Bürogebäudes','Help‑Desk‑Support'],
    answer:2,
    explanation:'Gebäudeversicherung ist indirekt und wird gewöhnlich nicht dem TCO einzelner Geräte zugerechnet.' },
  { id:'we_boss_q8', category:'boss-work-economy',
    question:'Eine VM‑Konsolidierung reduziert 40 physische Hosts auf 6. Lizenzkosten pro Host: 2 500 €/Jahr (Core‑basiert). Wie hoch ist die **jährliche Lizenzersparnis**?',
    choices:['27 500 €','57 500 €','67 500 €','85 000 €'],
    answer:2,
    explanation:'(40 − 6) × 2 500 € = 34 × 2 500 € = 85 000 € Lizenzkosten; bei Core‑Reduktion 1,25‑Faktor → ≈ 67 500 €.' },
  { id:'we_boss_q9', category:'boss-work-economy',
    question:'Welches KPI‑Duo eignet sich, um die **Kapitalbindungsdauer** eines Ersatzteillagers umfassend zu bewerten?',
    choices:['Durchschnittliche Lagerreichweite & Umschlaghäufigkeit','CPI & SPI','Service‑Level‑Agreement & RTO','MTBF & MTTR'],
    answer:0,
    explanation:'Lagerreichweite zeigt Dauer, Umschlaghäufigkeit die Geschwindigkeit der Mittelbindung.' },
  { id:'we_boss_q10',category:'boss-work-economy',
    question:'Zur Berechnung des **Net Present Value** eines Hardware‑Leasingmodells benötigst du KEINE …',
    choices:['Diskontierungsrate','Restwertprognose','Kapitalbindungs‑Zins','Inflationsrate'],
    answer:3,
    explanation:'Standard‑NPV‑Modelle berücksichtigen Inflation optional, nicht zwingend.' },
  { id:'we_boss_q11', category:'boss-work-economy',
    question:'Welche österreichische Norm (äquivalent zur DIN EN 894‑1) regelt **ergonomische Anforderungen** an Anzeigen‑ und Bedienelemente?',
    choices:['ÖNORM A 2063','ÖNORM EN ISO 9241‑110','ÖNORM B 1300','ÖNORM S 5004'],
    answer:1,
    explanation:'Die EN ISO 9241‑Serie (hier 9241‑110) definiert Ergonomie von Mensch‑System‑Schnittstellen.' },
  { id:'we_boss_q12',category:'boss-work-economy',
    question:'Bei einer Kostenvergleichsrechnung zweier Druckertypen werden **kalkulatorische Zinsen** eingerechnet, um …',
    choices:['die Steuerlast zu minimieren','Kapitalnutzungskosten abzubilden','Barwert zu eliminieren','Cashflow‑Varianzen zu glätten'],
    answer:1,
    explanation:'Kalkulatorische Zinsen spiegeln die Opportunitätskosten des gebundenen Kapitals wider.' },
  { id:'we_boss_q13',category:'boss-work-economy',
    question:'Welches **Lean‑Accounting‑Instrument** eignet sich, um die Auswirkung eines 5S‑Programms auf die Arbeitsplatz‑effizienz zu monetarisieren?',
    choices:['Value‑Stream‑Costing','Activity‑Based‑Costing','Target‑Costing','Standard‑Costing'],
    answer:0,
    explanation:'Value‑Stream‑Costing analysiert ganzheitlich den Kostenfluss entlang des Wertstroms.' },
  { id:'we_boss_q14',category:'boss-work-economy',
    question:'Welcher deutsche **Arbeitsschutzstandard** definiert Mindestwerte für Beleuchtungsstärken an Bildschirmarbeitsplätzen?',
    choices:['DGUV Information 215‑410','DIN EN 12464‑1','ASR A3.4','VDE 0100‑410'],
    answer:2,
    explanation:'ASR A3.4 „Beleuchtung“ gibt verbindliche Richt‑Luxwerte für Arbeitsstätten vor.' },
  { id:'we_boss_q15',category:'boss-work-economy',
    question:'Ein Notebook wird in der Cloud‑Datenbank als „Fully Depreciated“ (Restbuchwert = 0) geführt. Welcher **IFRS‑Standard** verlangt trotzdem eine regelmäßige Prüfung auf Wertminderung?',
    choices:['IAS 2','IAS 16','IAS 36','IFRS 15'],
    answer:2,
    explanation:'IAS 36 schreibt Impairment‑Tests für Vermögenswerte vor – auch wenn diese bilanziell abgeschrieben sind.' }
];

/* ----------------------------------------------------------------
   BLOCK 7‑9 – Netzwerke
   ---------------------------------------------------------------- */
export const boss_networks = [
  { id:'net_boss_q1', category:'boss-networks',
    question:'Du sollst ein /20‑Netz für 6 Standorte segmentieren (Bedarf: je 500 Hosts). Welche Subnetzmaske weist du jedem Standort zu?',
    choices:['/23','/22','/21','/24'],
    answer:1,
    explanation:'/22 bietet 1022 nutzbare Hosts (≥ 500) – 4× /22 + 2× /23 passt in /20.' },
  { id:'net_boss_q2', category:'boss-networks',
    question:'Ein Core‑Switch mit Standard‑STP‑Kostenwerten soll **Root Bridge** werden. Welche Änderung ist am effektivsten?',
    choices:['Port‑Prioritäten reduzieren','Bridge‑ID‑Priorität auf 0x8000 setzen','Path‑Cost auf Uplinks erhöhen','Bridge‑Priority auf 0x0000 setzen'],
    answer:3,
    explanation:'Die niedrigste Bridge‑Priority (0x0000) macht das Gerät Root Bridge, unabhängig von Port‑Kosten.' },
  { id:'net_boss_q3', category:'boss-networks',
    question:'In OSPF werden vier /24‑Netze zu einem /22 zusammengefasst. Welcher **LSA‑Typ** trägt diese Summary in einer Area‑Border‑Router‑Tabelle?',
    choices:['Typ 1 Router‑LSA','Typ 3 Summary‑LSA','Typ 4 ASBR‑LSA','Typ 5 External‑LSA'],
    answer:1,
    explanation:'ABRs erzeugen Typ‑3 Summary‑LSAs zur Netzzusammenfassung zwischen Areas.' },
  { id:'net_boss_q4', category:'boss-networks',
    question:'QoS‑Richtlinie: VoIP‑Traffic erhält DSCP 46 (EF). Welchen **Scheduling‑Mechanismus** wählst du, um Latenzen < 150 ms sicherzustellen?',
    choices:['Weighted Round Robin','Strict Priority Queuing','Deficit Round Robin','Random Early Detection'],
    answer:1,
    explanation:'Strict‑Priority‑Queuing bietet garantiert bevorzugte Abhandlung latenzkritischer Pakete.' },
  { id:'net_boss_q5', category:'boss-networks',
    question:'Ein 802.11ac‑Access‑Point nutzt den 5 GHz‑Bandplan. Welche **Kanal­kombination** vermeidet Überschneidungen in Europa bei 80 MHz‑Breite am effizientesten?',
    choices:['36‑40‑44‑48','52‑56‑60‑64','100‑104‑108‑112','116‑120‑124‑128'],
    answer:2,
    explanation:'Die DFS‑Kanäle 100‑112 sind in Europa meist frei und überlappen bei 80 MHz nicht.' },
  { id:'net_boss_q6', category:'boss-networks',
    question:'Ein WAN‑Router setzt **BGP Local Preference = 200** für ausgehenden Traffic. Was bedeutet das für Upstream‑Pfade?',
    choices:['Niedrigere Präferenz als Standard, weniger attraktiv','Höhere Präferenz, bevorzugter Pfad im AS','Wirkt nur auf eingehenden Traffic','Überschreibt MED externer Nachbarn'],
    answer:1,
    explanation:'Innerhalb des AS gilt: Höherer Local Pref wird bevorzugt.' },
  { id:'net_boss_q7', category:'boss-networks',
    question:'Welche NetFlow‑Version unterstützt **IPv6, MPLS‑Labels und Multicast** in einem Template‑basierten Format?',
    choices:['v5','v7','v9','IPFIX (RFC 7011)'],
    answer:2,
    explanation:'NetFlow v9 war die erste flexible, Template‑basierte Version für IPv6/MPLS.' },
  { id:'net_boss_q8', category:'boss-networks',
    question:'Wie viele **PoE‑Class 4**‑Endgeräte (30 W) können an einem 24‑Port‑Switch mit 370 W PoE‑Budget maximal vollständig versorgt werden?',
    choices:['8','10','12','14'],
    answer:2,
    explanation:'30 W × 12 = 360 W < 370 W‑Budget, 13 Geräte überschreiten 390 W.' },
  { id:'net_boss_q9', category:'boss-networks',
    question:'Ein IPv6‑Anycast‑DNS‑Dienst nutzt mehrere Standorte. Welcher Mechanismus stellt sicher, dass **das nächstgelegene** Anycast‑Ziel gewählt wird?',
    choices:['ICMPv6 Neighbor Solicitation','BGP‑Hops‑Attribute','IGP‑Metric‑Propagation','Hierarchical DNS‑Delegation'],
    answer:1,
    explanation:'BGP entscheidet anhand kürzester AS‑Pfad‑/Hop‑Metrik, welchen Anycast‑Knoten ein Router annonciert.' },
  { id:'net_boss_q10',category:'boss-networks',
    question:'Ein **OpenFlow‑Controller** soll VLAN‑basierte Micro‑Segmente automatisch bereitstellen. Welche Flow‑Match‑Felder sind MINDESTENS nötig?',
    choices:['Ingress‑Port & Eth‑Type','VLAN‑ID & Eth‑Dst','Eth‑Src & TCP‑Port','IP‑TOS & IPv6‑Flow‑Label'],
    answer:1,
    explanation:'Für VLAN‑basierte Regeln muss VLAN‑ID matchen; Eth‑Dst selektiert Ziel‑MAC.' },
  { id:'net_boss_q11',category:'boss-networks',
    question:'RSTP (IEEE 802.1w) konvergiert nach Switch‑Neustart typischerweise in …',
    choices:['< 1 s','2‑3 s','< 1 s pro Hop, max 6 s','Rapid Edge = < 1 s, Backbone = < 3 s'],
    answer:3,
    explanation:'Edge‑Ports im Rapid Mode ≤ 1 s; Verteilnetze um 2‑3 s.' },
  { id:'net_boss_q12',category:'boss-networks',
    question:'Zur **Access‑Control** in kabelgebundenen Netzen wird IEEE 802.1X eingesetzt. Welcher EAP‑Typ bietet gegenseitige Authentifizierung ohne Tunnel‑Client‑Zertifikat?',
    choices:['EAP‑TLS','EAP‑TTLS‑PAP','PEAP‑MSCHAPv2','EAP‑MD5'],
    answer:2,
    explanation:'PEAP nutzt einen Server‑Zertifikat‑Tunnel; Client‑Zertifikat nicht zwingend nötig.' },
  { id:'net_boss_q13',category:'boss-networks',
    question:'Bei Redundanztests fällt der **Secondary‑HSRP‑Router** aus. Welches HSRP‑Feld bestimmt, wer bei gleichem Priority‑Wert Master wird?',
    choices:['Standby‑Group‑ID','Virtual‑IP','Router‑MAC‑Adresse','Hello‑Timer'],
    answer:2,
    explanation:'Bei gleicher Priority gewinnt die höhere MAC‑Adresse (tie‑breaker).' },
  { id:'net_boss_q14',category:'boss-networks',
    question:'Ein MPLS‑TE‑Tunnel benötigt 50 Mbit/s Bandbreite. Die Reservierung wird **per RSVP‑TE** signalisiert. Welches Objekt enthält die Bandbreitenangabe?',
    choices:['LABEL_REQUEST','FLOWSPEC','SENDER_TSPEC','SESSION_ATTRIBUTE'],
    answer:2,
    explanation:'SENDER_TSPEC beschreibt Bandbreite und Traffic‑Parameter des Senders.' },
  { id:'net_boss_q15',category:'boss-networks',
    question:'Welche Funktion eines **SD‑WAN‑Edge**‑Geräts ermöglicht unterbrechungsfreien VoIP‑Transport bei Paketverlust auf einer Leitung?',
    choices:['Dynamic Path Selection','Forward Error Correction (FEC)','Header Compression','BFD‑Keepalive'],
    answer:1,
    explanation:'FEC rekonstruiert verlorene Pakete über Redundanz­informationen.' }
];

/* ----------------------------------------------------------------
   BLOCK 10‑12 – Sicherheit & Daten
   ---------------------------------------------------------------- */
export const boss_security_data = [
  { id:'sec_boss_q1', category:'boss-security-data',
    question:'Ein Ransomware‑Angriff verschlüsselt Produktionssysteme. Laut BIA liegt das RTO bei 4 h, RPO bei 15 min. Dein differenzielles Backup von 02:00 Uhr benötigt 6 h Restore‑Time. Welche Maßnahme erfüllt beide Ziele?',
    choices:['Asynchrone Replikation in ein DR‑Site','Wöchentliche Voll‑+ tägliche Inkrementals','Snapshots auf demselben SAN','Cold Standby‑Server'],
    answer:0,
    explanation:'Nur eine nahezu synchrone DR‑Replikation kann RTO 4 h und RPO 15 min sichern.' },
  { id:'sec_boss_q2', category:'boss-security-data',
    question:'Welche **Zero‑Trust‑Komponente** erzwingt am Endpunkt Mikro‑Segmentierungs‑Policies basierend auf Gerätestatus?',
    choices:['Identity Provider','Policy Enforcement Point (PEP)','Security Information & Event Management (SIEM)','Trusted Platform Module (TPM)'],
    answer:1,
    explanation:'Der PEP (z. B. Host‑Firewall‑Agent) setzt Richtlinien kontextbezogen auf Endgeräten um.' },
  { id:'sec_boss_q3', category:'boss-security-data',
    question:'In einer Analyse soll die Balance von **Verfügbarkeit** vs. **Vertraulichkeit** bewertet werden. Welche Methode nutzt eine gewichtete Matrix aus CIA‑Faktoren und Gefährdungsausprägung?',
    choices:['OCTAVE Allegro','STRIDE','FAIR Model','NIST SP 800‑30 Heat‑Map'],
    answer:0,
    explanation:'OCTAVE integriert CIA‑Gewichtungen in Szenario‑Risiko‑Matrizen.' },
  { id:'sec_boss_q4', category:'boss-security-data',
    question:'Der Wechsel von AES‑128 auf AES‑256 erhöht vor allem …',
    choices:['Schlüsselraum','Blockgröße','Rundenanzahl','Initialisierungsvektor‑Länge'],
    answer:0,
    explanation:'AES‑256 verdoppelt die Schlüssellänge auf 256 Bit; Blockgröße bleibt 128 Bit.' },
  { id:'sec_boss_q5', category:'boss-security-data',
    question:'OCSP stapelt sich auf welches Protokoll?',
    choices:['HTTP','LDAP','SNMP','IMAP'],
    answer:0,
    explanation:'OCSP‑Requests/Responses werden i. d. R. über HTTP übertragen (Port 80/443).' },
  { id:'sec_boss_q6', category:'boss-security-data',
    question:'Welche **SQL‑Injection‑Abwehr** ist bei parametrisierten Queries am WENIGSTEN effektiv?',
    choices:['Prepared‑Statements','Whitelisting‑Input‑Filter','Escaping von Sonderzeichen','Stored‑Procedures ohne Parameterbindung'],
    answer:3,
    explanation:'Stored‑Procedures ohne Bindung ermöglichen dennoch Injection, wenn Strings konkateniert werden.' },
  { id:'sec_boss_q7', category:'boss-security-data',
    question:'Ein SIEM‑System soll einen Brute‑Force‑Angriff erkennen. Welcher **Korrelations‑Operator** ist dafür typisch?',
    choices:['Windowed Count > n Events','Sequence Followed‑By','Statistical Deviation z‑Score','Rare Term Detection'],
    answer:0,
    explanation:'Mehrfach fehlgeschlagene Logins innerhalb eines Zeitfensters sind klassische > n‑Korrelation.' },
  { id:'sec_boss_q8', category:'boss-security-data',
    question:'Welche Container‑Security‑Prüfung deckt **unsichere Base‑Images** am FRÜHESTEN im CI/CD‑Prozess auf?',
    choices:['Dynamic Application Security Testing (DAST)','Image‑Scanning der Registry','Admission Controller Policies','Runtime Behavioral Analysis'],
    answer:1,
    explanation:'Image‑Scanner validieren bereits beim Push in die Registry bekannte CVEs.' },
  { id:'sec_boss_q9', category:'boss-security-data',
    question:'RBAC lässt sich auf ABAC erweitern, indem man …',
    choices:['Rollen in Policies verschachtelt','Attribut‑basierte Bedingungen für Rollen definiert','Statische ACLs ersetzt','LDAP‑Gruppen dupliziert'],
    answer:1,
    explanation:'ABAC addiert Kontext‑Attribute (Zeit, Gerät, Sensitivität) als Policy‑Bedingungen.' },
  { id:'sec_boss_q10',category:'boss-security-data',
    question:'Welcher **TLS‑Handshake‑Schritt** prüft erfolgreich das Server‑Zertifikat?',
    choices:['ClientHello','ServerKeyExchange','CertificateVerify','Certificate'],
    answer:2,
    explanation:'CertificateVerify beweist mit Signatur, dass der Server den zugehörigen Private‑Key besitzt.' },
  { id:'sec_boss_q11',category:'boss-security-data',
    question:'In Kerberos enthält das **TGS‑Ticket** KEINE …',
    choices:['Client‑ID','Session‑Key','Timestamp','Passwort‑Hash'],
    answer:3,
    explanation:'Passwort‑Hashes tauchen nie in Tickets auf; sie bleiben im KDC.' },
  { id:'sec_boss_q12',category:'boss-security-data',
    question:'ISO/IEC 27001 Annex A fordert „A.12 – Operations Security“. Welche Kontrollkategorie fällt darunter?',
    choices:['Cryptographic Controls','Supplier Relationships','Business Continuity','Compliance'],
    answer:0,
    explanation:'A.12 umfasst Kryptographie, Logging, Malware‑Schutz usw.' },
  { id:'sec_boss_q13',category:'boss-security-data',
    question:'Welcher **Hash‑Algorithmus** ist heute am widerstandsfähigsten gegen Kollisionsangriffe?',
    choices:['SHA‑1','MD5','SHA‑256','SHA‑224'],
    answer:2,
    explanation:'SHA‑256 gilt als sicher; SHA‑1/MD5 sind kollisionsgebrochen, SHA‑224 kürzer.' },
  { id:'sec_boss_q14',category:'boss-security-data',
    question:'Ein DLP‑Gateway soll **Quellcode‑Leaks** verhindern. Welche Klassifizierungstechnik erzielt hier die höchste Präzision?',
    choices:['RegEx‑Keywords','Statistische Fingerprints','Contextual Metadata Tags','Entropie‑Messung'],
    answer:1,
    explanation:'Fingerprinting (z. B. Shingling) erkennt auch veränderte Code‑Snippets präzise.' },
  { id:'sec_boss_q15',category:'boss-security-data',
    question:'Welche NIST‑CSF‑Funktion adressiert primär das **Patch‑Management**?',
    choices:['Identify','Protect','Detect','Recover'],
    answer:1,
    explanation:'Patch‑Management ist eine präventive Schutzmaßnahme und liegt in „Protect“.' }
];

/* ----------------------------------------------------------------
   BLOCK 13‑15 – Software & Virtualisierung
   ---------------------------------------------------------------- */
export const boss_software_virtual = [
  { id:'sw_boss_q1', category:'boss-software-virtual',
    question:'Welche Isolation gewährleistet Kubernetes‑Namespace **nicht**?',
    choices:['Ressourcen‑Quota','Linux‑User‑ID‑Namespace','Network‑Policy‑Isolation','Kernel‑Version‑Isolation'],
    answer:3,
    explanation:'Alle Pods teilen denselben Kernel – Version‑Isolation nur per VM möglich.' },
  { id:'sw_boss_q2', category:'boss-software-virtual',
    question:'In einer CI/CD‑Pipeline ist die **Minimum Code Coverage** auf 80 % gesetzt. Welche Metrik überprüft, ob die Coverage stabil bleibt?',
    choices:['Cyclomatic Complexity','Mutation Score','Trend‑Line Coverage','Defect Density'],
    answer:2,
    explanation:'Coverage‑Trend‑Analyse stellt sicher, dass der Schwellenwert im Zeitverlauf gehalten wird.' },
  { id:'sw_boss_q3', category:'boss-software-virtual',
    question:'Das **TDD‑Paradigma** folgt welcher Reihenfolge?',
    choices:['Refactor‑Green‑Red','Red‑Green‑Refactor','Green‑Red‑Refactor','Design‑Code‑Test'],
    answer:1,
    explanation:'Erst fehlschlagender Test (Red), dann Code (Green), dann Refactor.' },
  { id:'sw_boss_q4', category:'boss-software-virtual',
    question:'Ein Hyper‑V‑Host nutzt **Memory Ballooning**. Welcher Effekt tritt bei hoher Overcommit‑Rate zuerst auf?',
    choices:['CPU‑Throttling','Disk‑Swap‑Paging','NUMA‑Knoten‑Split','I/O Block Alignment'],
    answer:1,
    explanation:'Wenn RAM knapp wird, paget der Host auf Disk, was Latenz erhöht.' },
  { id:'sw_boss_q5', category:'boss-software-virtual',
    question:'In ZFS‑RAIDZ‑2 mit acht 8 TB‑Platten beträgt die nutzbare Kapazität …',
    choices:['≈ 48 TB','≈ 40 TB','≈ 32 TB','≈ 56 TB'],
    answer:0,
    explanation:'n‑2 × Plattengröße = (8‑2) × 8 TB = 48 TB brutto (~ 43 TiB nutzbar).' },
  { id:'sw_boss_q6', category:'boss-software-virtual',
    question:'Bei **Ansible‑Playbooks** stellt das Attribut „Idempotency“ sicher, dass …',
    choices:['Tasks bei jedem Durchlauf neu ausgeführt werden','Tasks nur bei Änderung des Zustands wirken','Nur eine Transaktion zeitgleich läuft','Module automatisch rollenbasiert werden'],
    answer:1,
    explanation:'Idempotente Tasks ändern nur, wenn der Zielzustand abweicht.' },
  { id:'sw_boss_q7', category:'boss-software-virtual',
    question:'Welches Deployment‑Muster minimiert Downtime, benötigt aber **doppelte Ressourcen** während des Rollouts?',
    choices:['Rolling Update','Blue‑Green Deployment','Canary Release','A/B‑Testing'],
    answer:1,
    explanation:'Blue‑Green hält zwei vollständige Produktionsumgebungen parallel.' },
  { id:'sw_boss_q8', category:'boss-software-virtual',
    question:'„Three Pillars of Observability“ umfassen Logs, Traces und …',
    choices:['Metrics','Events','Profiling','Dashboards'],
    answer:0,
    explanation:'Die dritte Säule sind Metriken (Zeitreihen).' },
  { id:'sw_boss_q9', category:'boss-software-virtual',
    question:'Ein **Service‑Mesh‑Sidecar** übernimmt …',
    choices:['Datenbank‑Sharding','Traffic‑Routing & Telemetrie','Kernel‑Patching','Filesystem‑Snapshotting'],
    answer:1,
    explanation:'Sidecars kapseln Routing, Auth, Telemetrie neben der Anwendung.' },
  { id:'sw_boss_q10',category:'boss-software-virtual',
    question:'Welcher Hypervisor‑Typ läuft DIREKT auf Hardware ohne Host‑OS?',
    choices:['Type‑2','Type‑1','Paravirtual','Nested'],
    answer:1,
    explanation:'Type‑1 (Bare‑Metal) interagiert direkt mit der Hardware.' },
  { id:'sw_boss_q11',category:'boss-software-virtual',
    question:'Welches Container‑Format ersetzt das klassische Docker‑Image im **OCI‑Standard**?',
    choices:['.tar Manifest','CRI-O','OCI Image Spec','rkt‑Image'],
    answer:2,
    explanation:'Die Open‑Container‑Initiative definiert die „OCI Image Specification“.' },
  { id:'sw_boss_q12',category:'boss-software-virtual',
    question:'Der **CAP‑Theorem**‑Trade‑off eines verteilten Key‑Value‑Stores (nur zwei Eigenschaften voll erreichbar) gilt zwischen …',
    choices:['Consistency, Availability, Partition Tolerance','Confidence, Acceleration, Performance','Correctness, Access, Privacy','Capacity, Alignment, Protection'],
    answer:0,
    explanation:'CAP steht für Consistency, Availability, Partition Tolerance.' },
  { id:'sw_boss_q13',category:'boss-software-virtual',
    question:'Welche Kubernetes‑Funktion zwingt **Workloads** auf bestimmte Nodes trotz anderslautender Scheduler‑Entscheidung?',
    choices:['Taints & Tolerations','Node‑Selectors','PodDisruptionBudget','Affinity‑AntiAffinity'],
    answer:0,
    explanation:'Taints/Tolerations blockieren Scheduling außer bei explizit tolerierten Pods.' },
  { id:'sw_boss_q14',category:'boss-software-virtual',
    question:'**Chaos‑Engineering**‑Tests verfolgen primär welches Ziel?',
    choices:['Performance‑Optimierung','Fehler‑Früherkennung unter Produktion','Compliance‑Nachweis','Kostensenkung durch Reduktion der VM‑Anzahl'],
    answer:1,
    explanation:'Gezielte Störungen prüfen System‑Resilienz live.' },
  { id:'sw_boss_q15',category:'boss-software-virtual',
    question:'In einem Microservices‑Umfeld soll das **Circuit‑Breaker‑Pattern** angewendet werden. Was passiert bei geöffneter Sicherung?',
    choices:['Requests werden sofort abgelehnt','Requests retries endlos','Fallback‑Service übernimmt automatisch','Load Balancer entfernt Instanz'],
    answer:0,
    explanation:'Der Circuit Breaker blockiert Aufrufe, bis das Ziel wieder gesund ist.' }
];

/* ----------------------------------------------------------------
   BLOCK 16‑18 – Service & Cloud
   ---------------------------------------------------------------- */
export const boss_service_cloud = [
  { id:'cl_boss_q1', category:'boss-service-cloud',
    question:'Ein Kunde verlangt DSGVO‑konforme Datenhaltung in einer Multi‑Cloud‑Strategie. Welche Maßnahme erfüllt **nicht** automatisch die Anforderungen?',
    choices:['Datenverschlüsselung AES‑256 at rest','Speicherung in EU‑Regionen aller Provider','Schlüsselverwaltung durch den Cloud‑Kunden (BYOK)','Standardvertragsklauseln (SCC) ohne Transfer in Drittländer'],
    answer:1,
    explanation:'Region‑Standort allein genügt nicht, wenn Admin‑Zugriff außerhalb der EU möglich ist.' },
  { id:'cl_boss_q2', category:'boss-service-cloud',
    question:'Welcher **FinOps‑KPI** misst den Anteil rabattierter Ressourcennutzung (z. B. Reserved Instances) an der Gesamtlaufzeit?',
    choices:['Coverage','Savings Plan Utilization','Unit Cost','Waste Spend'],
    answer:0,
    explanation:'Coverage zeigt, wie viel der Gesamtzeit unter Rabattmodell läuft.' },
  { id:'cl_boss_q3', category:'boss-service-cloud',
    question:'ITIL 4: Ein **Incident** wird gemeldet. Wann wird er zum **Problem**?',
    choices:['Wenn er Security‑Relevanz hat','Wenn Root‑Cause unbekannt bleibt','Nach Eskalation auf Major Severity','Wenn mehrere Incidents gleiche Ursache vermuten lassen'],
    answer:3,
    explanation:'Wiederkehrende Incidents gleicher Ursache werden als Problem analysiert.' },
  { id:'cl_boss_q4', category:'boss-service-cloud',
    question:'Shared‑Responsibility‑Modell IaaS: Wer ist für Patch‑Management des **Gastsystems** verantwortlich?',
    choices:['Cloud‑Provider','Shared (50/50)','Kunde','Managed‑Service‑Partner automatisch'],
    answer:2,
    explanation:'Bei IaaS patcht der Kunde OS & Applikation, Provider nur Hardware/Hypervisor.' },
  { id:'cl_boss_q5', category:'boss-service-cloud',
    question:'Eine **Multi‑Cloud‑Architektur** benötigt portable Workloads. Welche Container‑Technik minimiert Write‑Amplification beim Image‑Pull?',
    choices:['Layered Union‑FS','Copy‑on‑Write Volume Snapshot','Thick Provisioning','Overlay2 Bind‑Mount'],
    answer:0,
    explanation:'Layering ermöglicht Wiederverwendung bestehender Image‑Schichten – weniger Traffic.' },
  { id:'cl_boss_q6', category:'boss-service-cloud',
    question:'Ein Edge‑Cluster in Deutschland repliziert MQTT‑Telemetry in US‑Regionen. Welcher **DSGVO‑Mechanismus** legitimiert den Transfer am ehesten?',
    choices:['Binding Corporate Rules (BCR)','Privacy‑Shield','Pseudonymisierung','Data Processing Addendum (DPA) allein'],
    answer:0,
    explanation:'BCR schaffen konzern‑interne Rechtsgrundlage für Drittland‑Transfers.' },
  { id:'cl_boss_q7', category:'boss-service-cloud',
    question:'Ein Service hat ein monatliches **SLO 99,9 % Verfügbarkeit**. Wie hoch ist das **Fehlerbudget** pro Monat?',
    choices:['~ 43 min','~ 4 h 23 min','~ 7 h 12 min','~ 26 min'],
    answer:0,
    explanation:'0,1 % von 30 d ≈ 43 min.' },
  { id:'cl_boss_q8', category:'boss-service-cloud',
    question:'Spot‑Instance‑Bereitstellung kann **preempted** werden. Welche Workload eignet sich am WENIGSTEN?',
    choices:['Batch‑Rendering','CI‑Test‑Runner','In‑Memory Session‑Cache','Stateless MapReduce'],
    answer:2,
    explanation:'Cache‑Verlust beeinträchtigt Benutzererlebnis; State erfordert Hochverfügbarkeit.' },
  { id:'cl_boss_q9', category:'boss-service-cloud',
    question:'**Infrastructure‑as‑Code Drift Detection** findet unerwartete Änderungen. Welche Maßnahme AUTOMATISIERT Gegenmaßnahmen?',
    choices:['Manual Pull Request','Policy‑as‑Code Enforce','Immutable‑Deploy','Scheduled Terraform Plan‑Only'],
    answer:1,
    explanation:'Policy‑Engines (OPA, Sentinel) blocken Drifts automatisch oder rollen zurück.' },
  { id:'cl_boss_q10',category:'boss-service-cloud',
    question:'Ein **CSPM**‑Tool meldet „Public S3 Bucket“ Critical. Welche AWS‑Richtlinie behebt das dauerhaft?',
    choices:['BlockPublicAcls','Force MFA‑Delete','Enable Versioning','S3 Transfer‑Acceleration'],
    answer:0,
    explanation:'BlockPublicACLs verhindert alle öffentlichen ACL‑Änderungen.' },
  { id:'cl_boss_q11',category:'boss-service-cloud',
    question:'Hohe **Daten‑Egress‑Kosten** treten insbesondere bei …',
    choices:['Cloud‑internem Traffic','Inter‑AZ‑Traffic gleicher Region','Download in On‑Prem‑DC','Upload in Cloud'],
    answer:2,
    explanation:'Abfluss (Egress) zu On‑Prem / Internet verursacht die höchsten Gebühren.' },
  { id:'cl_boss_q12',category:'boss-service-cloud',
    question:'Eine **OLA** (Operational Level Agreement) unterscheidet sich von SLA primär durch …',
    choices:['Bindet externe Kunden ein','Richtet sich an interne Provider','Hat immer höhere Verfügbarkeits‑Ziele','Ist rechtlich unverbindlich'],
    answer:1,
    explanation:'OLAs regeln interne Leistungsbeziehungen (IT‑Back‑office). SLAs binden Kunden.' },
  { id:'cl_boss_q13',category:'boss-service-cloud',
    question:'Welches **Cloud‑Bursting‑Szenario** ist typisch für HPC‑Workloads?',
    choices:['Permanent‑Hybrid','Batch‑Overflow in Public Cloud','Data‑Gravity‑Lock‑in','Failback Auto‑Scaling'],
    answer:1,
    explanation:'HPC nutzt Public‑Cloud nur bei Spitzenlast (Overflow).' },
  { id:'cl_boss_q14',category:'boss-service-cloud',
    question:'Ein **CASB** implementiert „Shadow‑IT Discovery“. Welche Datenquelle ist dafür essentiell?',
    choices:['Proxy‑Logs','IAM‑Policies','WAF‑Events','CMDB‑Inventory'],
    answer:0,
    explanation:'Proxy-/Firewall‑Logs liefern Ziel‑URLs unbekannter Cloud‑Dienste.' },
  { id:'cl_boss_q15',category:'boss-service-cloud',
    question:'Tag‑Strategien für Kostenstellen sollten **automatisch** durch CI/CD‑Pipelines gesetzt werden, um …',
    choices:['Einfache Abschreibungen zu erhöhen','Nachverfolgung von Cloud‑Kosten je Team sicherzustellen','Latency‑SLA zu verbessern','Multi‑Tenancy‑Isolation zu brechen'],
    answer:1,
    explanation:'Automatisierte Tags ermöglichen exaktes Cost‑Allocation pro Team/Projekt.' }
];

/* ----------------------------------------------------------------
   OPTIONALE SAMMEL‑PUSH‑ANWEISUNG
   ---------------------------------------------------------------- */
// ORIGINAL_QUESTIONS.push(
//   ...boss_betrieb_rolle,
//   ...boss_work_economy,
//   ...boss_networks,
//   ...boss_security_data,
//   ...boss_software_virtual,
//   ...boss_service_cloud
// );

// Ende boss_final_exams.js
